exp_name: cifar10_momentum_randaug_2_5_cutout_checkpoint_test

trainer_name: CIFARTrainer

model:
  num_classes: 10

trainer:
  num_epochs: 10
  save_frequency: 5 # epochs
  log_frequency: 390 # iterations
  val_frequency: 390 # iterations
  ema_decay_rate: 0.999

train_dataset:
  root: /home/kuohsin/workspace/dataset
  train: True

val_dataset:
  root: /home/kuohsin/workspace/dataset
  train: False

train_dataloader:
  batch_size: 128
  num_workers: 4
  drop_last: True
  shuffle: True
  pin_memory: True

val_dataloader:
  batch_size: 256
  num_workers: 4
  drop_last: False
  shuffle: False
  pin_memory: True

optimizer:
  lr: 1.e-1
  weight_decay: 5.e-4
  momentum: 0.9
  # nesterov: True

scheduler:
  T_max: 200
  eta_min: 1.e-4
