exp_name: uda_cifar10_all_tricks_cutout_all_simple_aug

trainer_name: UDATrainer

model:
  num_classes: 10

trainer:
  num_iterations: 500000
  save_frequency: 900000 # iterations
  log_frequency: 100 # iterations
  val_frequency: 100 # iterations
  semi_supervised: True
  confidence_threshold: 0.8
  softmax_temperature: 0.4
  ema_decay_rate: 0.999

train_supervised_dataset:
  root: /home/kuohsin/workspace/dataset
  train: True
  supervised_count: 4000

train_unsupervised_dataset:
  root: /home/kuohsin/workspace/dataset
  train: True
  supervised_count: -4000

val_dataset:
  root: /home/kuohsin/workspace/dataset
  train: False

train_supervised_dataloader:
  batch_size: 64
  num_workers: 4
  drop_last: True
  shuffle: True
  pin_memory: True

train_unsupervised_dataloader:
  batch_size: 448
  num_workers: 4
  drop_last: True
  shuffle: True
  pin_memory: True

val_dataloader:
  batch_size: 256
  num_workers: 4
  drop_last: False
  shuffle: False
  pin_memory: True

optimizer:
  lr: 3.e-2
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: True

scheduler:
  T_max: 500000
  eta_min: 0.005
